# Generated by Django 5.2 on 2025-04-19 18:29

import profile.models
import profile.storages

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=profile.storages.OverwriteStorage,
                upload_to=profile.models.get_avatar_upload_path,
            ),
        ),
    ]
