# Generated by Django 5.2 on 2025-04-18 20:38

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('username', models.TextField(blank=True, null=True)),
                ('avatarUrl', models.URLField(blank=True, null=True)),
                ('nickname', models.TextField()),
                ('gameName', models.TextField(blank=True)),
                ('gameId', models.BigIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'externalGuid',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ('address', models.GenericIPAddressField()),
                (
                    'port',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ]
                    ),
                ),
                ('owner', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('preferredGameName', models.TextField(blank=True)),
                ('preferredGameId', models.BigIntegerField()),
                ('maxPlayers', models.IntegerField()),
                ('netVersion', models.IntegerField()),
                ('hasPassword', models.BooleanField()),
                ('players', models.JSONField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
    ]
