# Generated by Django 5.2 on 2025-04-21 22:42

import citra_account.models
import citra_account.storages
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citra_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=citra_account.storages.OverwriteStorage(base_url='/account/avatars/', location=pathlib.PurePosixPath('/mnt/c/Users/sebas/repos/citra-backend/app/media/avatars')), upload_to=citra_account.models.get_avatar_upload_path),
        ),
    ]
