# Generated by Django 5.2 on 2025-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('citra_account', '0002_account_token_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(default='dfjadkfjskadsfj', max_length=128),
            preserve_default=False,
        ),
    ]
