# Generated by Django 6.0.3 on 2026-03-13 14:39

import pathlib

from django.db import migrations, models

import citra_account.models
import citra_account.storages


class Migration(migrations.Migration):
    dependencies = [
        ('citra_account', '0003_alter_account_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=citra_account.storages.OverwriteStorage(
                    base_url='/account/avatars/',
                    location=pathlib.PurePosixPath(
                        '/home/arma/repos/citra-backend-v2/app/media/avatars'
                    ),
                ),
                upload_to=citra_account.models.get_avatar_upload_path,
            ),
        ),
    ]
