# Generated by Django 6.0.3 on 2026-03-13 15:43

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_anonymous_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    user, created = User.objects.get_or_create(username='anonymous')

    if created:
        user.password = make_password(None)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('citra_account', '0004_alter_account_avatar'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_anonymous_user, migrations.RunPython.noop),
    ]

